import pandas as pd
from config import Connection
import psycopg2

conn = Connection(psycopg2)

tipos_productos = []
ingresos = []
gastos = []
cod_pais = []
continentes = []
paises = []
trimestres = []
anios = []

dim_tipo_productos = []
dim_categoria_productos = []


def insert_db_dim():
    i = 0
    try:
        while i < len(dim_tipo_productos):
            print(dim_tipo_productos[i],dim_categoria_productos[i]) 
            conn.curExecute(f"""
                insert into python_appol_dim("tipo_producto","categoria_producto")
                values('{dim_tipo_productos[i]}','{dim_categoria_productos[i]}')
            """)
            i += 1

    except Exception as e:
        print(e)


def insert_db_fact():
    i = 0
    try:
        while i < len(tipos_productos):
            print(tipos_productos[i],ingresos[i],gastos[i],cod_pais[i],continentes[i],paises[i],trimestres[i], anios[i]) 
            conn.curExecute(f"""
                insert into python_appol_fact("tipo_producto","ingresos","gastos","cod_pais","continente","pais","trimestre","anio")
                values('{tipos_productos[i]}',{ingresos[i]},{gastos[i]},'{cod_pais[i]}','{continentes[i]}','{paises[i]}','{trimestres[i]}',{anios[i]})
            """)
            i += 1

    except Exception as e:
        print(e)


def iterator_dim(df):
    iterator_type_product = df['Tipo_Producto']
    iterator_product_category = df['Categoria_Producto']

    for producto in iterator_type_product: 
        # print(producto)
        dim_tipo_productos.append(producto)

    for categoria in iterator_product_category: 
        # print(producto)
        dim_categoria_productos.append(categoria)



def iterator_fact(df):
    iterator_type_product = df['Tipo_Producto']
    iterator_ingresos = df['Ingresos']
    iterator_gastos = df['Gastos']
    iterator_cod_pais = df['Cod_Pais']
    iterator_continente = df['Continente']
    iterator_pais = df['Pais']
    iterator_trimestre = df['Trimestre']
    iterator_anio = df['Anio']

    for producto in iterator_type_product: 
        # print(producto)
        tipos_productos.append(producto)
    
    for ingreso in iterator_ingresos: 
        # print(ingreso)
        ingresos.append(ingreso)

    for gasto in iterator_gastos: 
        # print(gasto)
        gastos.append(gasto)

    for cod in iterator_cod_pais: 
        # print(cod)
        cod_pais.append(cod)
        
    for continente in iterator_continente: 
        # print(continente)
        continentes.append(continente)
        
    for pais in iterator_pais: 
        # print(pais)
        paises.append(pais)
        
    for trimestre in iterator_trimestre: 
        # print(trimestre)
        trimestres.append(trimestre)
        
    for anio in iterator_anio: 
        # print(anio)
        anios.append(anio)


def creation_table():
    conn.curExecute("""
        create table "python_appol_dim"(
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        tipo_producto VARCHAR(100),
        categoria_producto VARCHAR(100)
    );


    create table "python_appol_fact"(
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        tipo_producto VARCHAR(100),
        ingresos float8,
        gastos float8,
        cod_pais char(3),
        continente VARCHAR(100),
        pais VARCHAR(100),
        trimestre char(2),
        anio CHAR(10) 

    );


    """)


def read_fact_dim_csv():
    path_fact_linux = '/home/alexis/Escritorio/alexis/appol/appol_clean_final.csv'
    path_dim_linux = '/home/alexis/Escritorio/alexis/appol/table_products_clean.csv'
    path_fact_windows = 'C:/Users/alexi/OneDrive/Escritorio/alexis/appol/appol_clean_final.csv'
    path_dim_windows = 'C:/Users/alexi/OneDrive/Escritorio/alexis/appol/table_products_clean.csv'
    df_fact_windows = pd.read_csv(path_fact_windows)
    df_dim_windows = pd.read_csv(path_dim_windows)

    iterator_fact(df_fact_windows)
    iterator_dim(df_dim_windows)


if __name__ == '__main__':
    
    print("Create the dimension and fact tables?")
    print("1 = Yes or 2 = No")
    response = str(input())
    
    if response == "1":
        creation_table()

    elif response == "2":
        print('Insert data into dim table?')
        print('1 = Yes or 2 = No')
        response_two = str(input())

        if response_two == "1":
            read_fact_dim_csv()
            insert_db_dim()

        elif response_two == "2":
            print('Insert data into fact table?')
            print('1 = Yes or 2 = No')
            response_three = str(input())

            if response_three == "1":
                read_fact_dim_csv()
                insert_db_fact()
            
            else:
                print("Unchanged")
